In [1]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np 
from NN import Layer_Dense, Train_Model

In [2]:
# eash row is an image
# 42000 images each having 784 pixels (featres)
# first column is the number vale, the rest 784 is the image pixels
# (42000, 785)
data = pd.read_csv('train.csv')
data = np.array(data)
data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]])

In [3]:
np.random.shuffle(data) # shuffle before splitting into test and training sets


data_test = data[0:1000,:].T #1000 image for testing, each col is an image 
m, n = data.shape

Y_test = data_test[0,:] 
X_test = data_test[1:n,:]
X_test = X_test / 255.

In [4]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
data_train = data[1000:m].T
Y_train = data_train[0,:]
X_train = data_train[1:n,:]
X_train = X_train / 255.

In [ ]:
model = [Layer_Dense(10,784,'ReLU'), Layer_Dense(30,10,'ReLU'), Layer_Dense(10, 30,'Softmax')]

train = Train_Model(model,X_train, Y_train, epochs=200, learning_rate=0.1)
train.Train()

epoch:  0
[9 0 0 ... 6 9 5] [4 7 4 ... 5 1 5]
acc 0.08892682926829268
----------------------------------------------
epoch:  10
[9 0 0 ... 6 9 9] [4 7 4 ... 5 1 5]
acc 0.13097560975609757
----------------------------------------------


In [ ]:
X_test[0:,1].shape

In [ ]:
example = X_test[0:,50].reshape(784,1)
train.predict_probability(example)

In [ ]:
train.predict_onehot(example)

In [ ]:
test_predictions = train.make_predictions(X_test)

In [ ]:
train.get_accuracy(test_predictions, Y_test)